### ISSUE TITLE
Missing macros folder

### ISSUE THREAD

**Issue by tkersten09** [triflesoft/curio-http-server#7]
It looks like that the `macros` folder in `examples` is missing, which is required as an import in the  	`test_binders_item.html` file.

See the first line of `test_binders_item.html`:
`{% import 'macros/view_semantic.html' as view %}<!DOCTYPE html>
...`

Would be nice to have, so that i can check out the binders in its full blume :)

**Comment by adontz** [comment]
This file is in
https://github.com/triflesoft/curio-http-server/tree/master/curio_http_server/core/templates/macros
